In [1]:
import pandas as pd
import numpy as np

In [2]:
pisa12 = pd.read_csv('pisa2012.csv', encoding = "ISO-8859-1")

D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (15,16,17,21,22,23,24,25,26,30,31,36,37,45,65,123,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,475) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [20]:
pisa12.columns.get_loc('CNT')

1

In [3]:
pisa_scores = pisa12.filter(pisa12.columns[1:551], axis=1)

In [26]:
pisa_scores.columns.get_loc('ST73Q01')

59

In [27]:
pisa_scores.columns.get_loc('PV1MATH')

380

In [7]:
pisa_scores = pisa_scores.drop(pisa_scores.columns[1:4], axis =1)

In [9]:
pisa_scores = pisa_scores.drop(pisa_scores.columns[2:8], axis =1)

In [12]:
pisa_scores = pisa_scores.drop(pisa_scores.columns[4:17], axis =1)

In [16]:
pisa_scores = pisa_scores.drop(pisa_scores.columns[5:9], axis =1)

In [ ]:
pisa_scores = pisa_scores.drop(pisa_scores.columns[7:11], axis =1)

In [28]:
pisa_scores = pisa_scores.drop(pisa_scores.columns[60:380], axis =1)

In [29]:
pisa_scores.to_csv('pisa_score.csv')

In [3]:
pisa_score = pd.read_csv('pisa_score.csv', encoding = "ISO-8859-1")

D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (7,8,13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
pisa_score

,CNT,NC,ST04Q01,ST13Q01,ST14Q01,ST14Q02,ST14Q03,ST14Q04,ST15Q01,ST17Q01,...,PV1READ,PV2READ,PV3READ,PV4READ,PV5READ,PV1SCIE,PV2SCIE,PV3SCIE,PV4SCIE,PV5SCIE
0,Albania,Albania,Female,<ISCED level 3A>,No,No,No,No,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,249.5762,254.3420,406.8496,175.7053,218.5981,341.7009,408.8400,348.2283,367.8105,392.9877
1,Albania,Albania,Female,<ISCED level 3A>,Yes,Yes,No,No,Working full-time <for pay>,<ISCED level 3A>,...,406.2936,349.8975,400.7334,369.7553,396.7618,548.9929,471.5964,471.5964,443.6218,454.8116
2,Albania,Albania,Female,"<ISCED level 3B, 3C>",Yes,Yes,Yes,No,Working full-time <for pay>,<ISCED level 3A>,...,401.2100,404.3872,387.7067,431.3938,401.2100,499.6643,428.7952,492.2044,512.7191,499.6643
3,Albania,Albania,Female,"<ISCED level 3B, 3C>",No,No,No,No,Working full-time <for pay>,<ISCED level 3A>,...,547.3630,481.4353,461.5776,425.0393,471.9036,438.6796,481.5740,448.9370,474.1141,426.5573
4,Albania,Albania,Female,She did not complete <ISCED level 1>,No,No,No,No,Working part-time <for pay>,"<ISCED level 3B, 3C>",...,311.7707,141.7883,293.5015,272.8495,260.1405,361.5628,275.7740,372.7527,403.5248,422.1746
5,Albania,Albania,Female,"<ISCED level 3B, 3C>",No,No,No,No,"Not working, but looking for a job",<ISCED level 2>,...,378.2544,366.3398,387.7861,335.3617,219.3924,384.3156,358.2059,405.7628,403.8978,325.5688
6,Albania,Albania,Female,"<ISCED level 3B, 3C>",No,Yes,No,No,Working full-time <for pay>,<ISCED level 3A>,...,373.2503,374.0446,401.8454,338.3006,373.2503,508.1499,462.4580,499.7576,519.3398,466.1880
7,Albania,Albania,Male,<ISCED level 3A>,No,Yes,No,No,Working full-time <for pay>,<ISCED level 3A>,...,567.7589,465.1099,431.4282,535.6811,582.9958,611.2831,596.3633,554.4013,513.3719,519.8993
8,Albania,Albania,Female,<ISCED level 3A>,NaN,NaN,NaN,NaN,Working part-time <for pay>,<ISCED level 3A>,...,313.9153,332.9787,316.2982,391.7577,278.9657,373.0325,317.0832,376.7624,409.3995,382.3573
9,Albania,Albania,Female,<ISCED level 3A>,No,No,No,No,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,454.5082,420.3529,360.7796,450.5366,323.4470,404.2708,343.6591,339.9291,335.2667,287.7098
10,Albania,Albania,Female,<ISCED level 3A>,Yes,Yes,No,No,Working full-time <for pay>,<ISCED level 3A>,...,550.0637,527.8230,545.2978,564.3613,569.9215,438.0269,455.7441,473.4614,466.0015,465.0690
11,Albania,Albania,Female,<ISCED level 3A>,NaN,NaN,NaN,Yes,Working full-time <for pay>,<ISCED level 3A>,...,229.1624,265.7007,125.9021,161.6460,257.7576,340.1156,296.2887,182.5252,189.9851,290.6938
12,Albania,Albania,Female,<ISCED level 2>,No,No,No,No,"Other (e.g. home duties, retired)",He did not complete <ISCED level 1>,...,162.9964,190.0029,279.7600,157.4362,104.2174,150.5408,240.0597,217.6800,164.5282,199.0302
13,Albania,Albania,Female,<ISCED level 3A>,No,No,No,Yes,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,563.0904,502.7228,464.5959,463.0073,517.8147,489.5002,546.3819,501.6225,498.8251,490.4327
14,Albania,Albania,Male,<ISCED level 2>,No,No,No,No,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,259.8119,291.0878,370.4804,273.4450,221.3186,264.5841,290.6938,387.6725,286.9638,242.2044
15,Albania,Albania,Male,<ISCED level 2>,Yes,No,No,No,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,376.3346,329.0198,396.3832,343.4548,430.0649,402.5923,359.6979,420.3096,344.7781,359.6979
16,Albania,Albania,Female,<ISCED level 2>,No,No,No,No,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,194.7688,208.2721,177.2940,182.8541,181.2655,145.2257,167.6054,211.4323,301.8836,303.7486
17,Albania,Albania,Male,<ISCED level 2>,No,NaN,NaN,NaN,"Other (e.g. home duties, retired)",<ISCED level 2>,...,566.1550,588.6094,599.0347,590.2133,449.8729,511.0407,483.0660,522.2305,483.0660,504.5132
18,Albania,Albania,Female,<ISCED level 3A>,Yes,Yes,No,Yes,Working full-time <for pay>,"<ISCED level 3B, 3C>",...,362.6065,367.3724,303.8276,345.9260,372.1382,350.3730,405.3898,346.6430,352.2380,345.7106
19,Albania,Albania,Female,<ISCED level 3A>,No,No,No,No,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,475.1603,329.8015,379.8430,576.0376,529.1733,509.2689,419.7501,408.5602,483.1593,438.3999
20,Albania,Albania,Female,<ISCED level 3A>,No,No,No,No,"Other (e.g. home duties, retired)",NaN,...,410.2651,420.5912,458.7180,485.7246,366.5781,356.9004,396.9974,427.7695,428.7020,364.3603
21,Albania,Albania,Male,<ISCED level 2>,No,No,No,No,Working part-time <for pay>,<ISCED level 3A>,...,459.4161,488.2861,402.4780,406.4877,444.9811,371.9135,483.8120,335.5464,439.9851,413.8754
22,Albania,Albania,Female,<ISCED level 2>,No,No,No,No,"Other (e.g. home duties, retired)",<ISCED level 2>,...,258.2342,219.3130,295.5667,284.4464,266.1773,277.3592,267.1018,274.5617,271.7643,222.3424
23,Albania,Albania,Female,<ISCED level 2>,No,No,No,No,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,392.4726,420.2734,395.6498,491.7613,363.0831,468.5192,465.7217,448.9370,440.5446,355.6882
24,Albania,Albania,Male,<ISCED level 2>,No,No,No,No,"Other (e.g. home duties, retired)",<ISCED level 2>,...,317.4718,335.9165,342.3321,360.7768,288.6018,315.8709,323.3308,290.6938,300.0186,294.4237
25,Albania,Albania,Female,<ISCED level 2>,No,No,No,No,"Not working, but looking for a job",<ISCED level 3A>,...,345.6083,302.7155,359.1115,440.9255,374.2034,349.4405,381.1451,384.8750,395.1324,362.4953
26,Albania,Albania,Female,<ISCED level 3A>,No,No,No,Yes,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,388.5805,402.0837,411.6154,385.4032,403.6723,361.5628,447.3517,352.2380,399.7949,440.8243
27,Albania,Albania,Male,<ISCED level 3A>,Yes,NaN,NaN,NaN,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,466.7138,329.5812,407.3698,364.0648,494.7819,459.1943,365.0131,405.1100,384.5953,364.0806
28,Albania,Albania,Female,<ISCED level 2>,No,No,No,No,"Other (e.g. home duties, retired)",<ISCED level 2>,...,365.5455,465.6285,240.8388,259.1079,285.3201,268.1276,359.5114,273.7225,247.6128,297.9672
29,Albania,Albania,Female,<ISCED level 3A>,No,Yes,No,No,Working full-time <for pay>,<ISCED level 3A>,...,569.1271,502.4051,531.0003,542.9149,537.3547,542.4655,468.7990,509.8284,542.4655,579.7650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485460,Vietnam,Viet Nam,Male,<ISCED level 1>,No,No,NaN,No,"Other (e.g. home duties, retired)",He did not complete <ISCED level 1>,...,457.8924,414.5873,445.0613,427.4185,419.3990,524.7482,506.0985,517.2883,508.8959,492.1112
485461,Vietnam,Viet Nam,Male,She did not complete <ISCED level 1>,No,No,NaN,No,"Other (e.g. home duties, retired)",He did not complete <ISCED level 1>,...,477.2995,523.0103,509.3773,510.1792,478.1014,550.8579,615.1996,532.2081,590.9549,580.6975
485462,Vietnam,Viet Nam,Female,NaN,NaN,NaN,NaN,NaN,NaN,He did not complete <ISCED level 1>,...,524.4075,454.5082,488.6635,491.0465,485.4863,549.8322,461.2458,485.4905,543.3047,540.5073
485463,Vietnam,Viet Nam,Male,She did not complete <ISCED level 1>,No,No,NaN,No,Working full-time <for pay>,<ISCED level 3A>,...,462.5437,529.1051,450.5145,463.3456,445.7028,549.9254,570.4401,590.0224,568.5752,583.4950
485464,Vietnam,Viet Nam,Male,<ISCED level 2>,No,No,NaN,No,Working full-time <for pay>,<ISCED level 2>,...,524.4538,457.8924,493.9799,486.7624,481.1488,540.6005,517.2883,562.0477,542.4655,498.6386
485465,Vietnam,Viet Nam,Male,She did not complete <ISCED level 1>,No,No,NaN,No,"Other (e.g. home duties, retired)",He did not complete <ISCED level 1>,...,536.6434,528.6239,559.8998,528.6239,518.1987,599.1608,575.8486,537.6166,555.3338,608.4856
485466,Vietnam,Viet Nam,Male,She did not complete <ISCED level 1>,No,No,NaN,No,Working part-time <for pay>,He did not complete <ISCED level 1>,...,423.0880,443.9385,432.7113,379.7829,426.2957,512.2529,588.7169,526.2402,580.3245,559.8098
485467,Vietnam,Viet Nam,Female,She did not complete <ISCED level 1>,No,No,NaN,No,Working full-time <for pay>,<ISCED level 1>,...,475.2397,469.6795,522.8983,470.4738,518.9267,457.8888,461.6188,490.5259,462.5513,441.1041
485468,Vietnam,Viet Nam,Female,She did not complete <ISCED level 1>,No,No,NaN,No,Working part-time <for pay>,<ISCED level 1>,...,453.3962,469.2824,487.5515,458.1620,492.3174,575.6621,510.3879,525.3077,501.0630,574.7296
485469,Vietnam,Viet Nam,Female,She did not complete <ISCED level 1>,No,No,NaN,No,Working full-time <for pay>,He did not complete <ISCED level 1>,...,456.0968,424.3244,449.7423,436.2391,419.5585,527.2659,502.0888,519.8060,460.1268,465.7217
485470,Vietnam,Viet Nam,Male,<ISCED level 1>,No,No,NaN,No,"Other (e.g. home duties, retired)",He did not complete <ISCED level 1>,...,399.3504,401.7562,431.4282,354.4415,413.7854,467.8665,466.0015,502.3685,452.9467,472.5289
485471,Vietnam,Viet Nam,Male,<ISCED level 2>,No,No,NaN,No,NaN,<ISCED level 3A>,...,548.4320,484.2764,494.7017,498.7114,493.0978,552.7229,507.9634,539.6680,523.8157,528.4782
485472,Vietnam,Viet Nam,Male,<ISCED level 1>,No,No,NaN,No,"Other (e.g. home duties, retired)",<ISCED level 1>,...,486.6020,464.1476,460.1378,480.9884,438.4853,569.5076,564.8452,608.6721,553.6554,573.2376
485473,Vietnam,Viet Nam,Female,<ISCED level 1>,No,No,NaN,No,Working full-time <for pay>,<ISCED level 2>,...,443.3879,464.0399,539.4994,446.5651,448.1537,456.6766,521.0183,521.9508,507.9634,506.0985
485474,Vietnam,Viet Nam,Male,<ISCED level 2>,No,No,NaN,No,Working part-time <for pay>,NaN,...,418.7575,462.8644,409.9361,409.9361,429.9847,481.6673,504.9795,457.4226,429.4480,489.1272
485475,Vietnam,Viet Nam,Male,She did not complete <ISCED level 1>,No,No,NaN,No,Working part-time <for pay>,He did not complete <ISCED level 1>,...,481.9507,427.4185,474.7332,517.2363,444.2593,494.9086,459.4741,473.4614,540.6005,492.1112
485476,Vietnam,Viet Nam,Female,<ISCED level 2>,No,No,NaN,No,"Other (e.g. home duties, retired)",<ISCED level 2>,...,493.4294,441.0049,511.6985,452.9196,371.8999,491.0854,464.0433,554.4946,517.1951,439.7986
485477,Vietnam,Viet Nam,Female,She did not complete <ISCED level 1>,No,No,NaN,No,"Other (e.g. home duties, retired)",<ISCED level 1>,...,530.7620,428.2960,441.0049,505.3440,475.1603,503.3010,464.1365,494.9086,516.3558,516.3558
485478,Vietnam,Viet Nam,Female,<ISCED level 1>,No,No,NaN,No,"Other (e.g. home duties, retired)",He did not complete <ISCED level 1>,...,442.7524,491.9996,452.2841,475.3191,483.2622,485.2107,496.4006,510.3879,494.5356,488.0082
485479,Vietnam,Viet Nam,Male,<ISCED level 1>,No,No,NaN,No,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,418.5971,477.1391,452.2788,506.8110,529.2655,473.1816,523.5360,489.9664,540.3208,528.1984
485480,Vietnam,Viet Nam,Male,<ISCED level 2>,No,No,NaN,No,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,452.4392,429.1827,431.5886,458.8547,480.5072,547.6874,501.9955,476.8184,533.7001,484.2783
485481,Vietnam,Viet Nam,Male,NaN,No,No,NaN,Yes,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,459.4161,429.7441,416.9130,415.3091,479.4647,473.4614,421.2421,410.9847,463.2040,513.5584
485482,Vietnam,Viet Nam,Female,"<ISCED level 3B, 3C>",No,No,NaN,Yes,Working full-time <for pay>,"<ISCED level 3B, 3C>",...,509.3156,475.9546,488.6635,459.2741,520.4359,477.1913,482.7863,480.9213,516.3558,497.7061
485483,Vietnam,Viet Nam,Female,<ISCED level 3A>,No,No,NaN,No,Working full-time <for pay>,<ISCED level 3A>,...,482.3090,524.4075,474.3659,530.7620,492.6351,533.4204,525.0280,519.4330,528.7579,553.0026
485484,Vietnam,Viet Nam,Male,She did not complete <ISCED level 1>,No,No,NaN,No,"Other (e.g. home duties, retired)",<ISCED level 1>,...,433.8340,460.2982,430.6262,488.3663,523.6519,480.6416,497.4263,529.1309,503.0213,485.3040
485485,Vietnam,Viet Nam,Female,<ISCED level 2>,No,No,NaN,No,"Other (e.g. home duties, retired)",He did not complete <ISCED level 1>,...,460.2272,476.1134,472.9362,472.1419,481.6736,559.8098,528.1052,519.7128,535.5651,538.3626
485486,Vietnam,Viet Nam,Male,She did not complete <ISCED level 1>,No,No,NaN,No,"Other (e.g. home duties, retired)",<ISCED level 2>,...,490.9325,479.7053,448.4294,565.5134,451.6372,538.7355,493.9761,493.0436,561.1153,535.0056
485487,Vietnam,Viet Nam,Male,<ISCED level 1>,No,No,NaN,No,Working full-time <for pay>,<ISCED level 2>,...,462.6239,514.7503,434.5558,457.8122,511.5425,536.8706,571.3726,488.3812,548.9929,563.9127
485488,Vietnam,Viet Nam,Male,<ISCED level 2>,No,No,NaN,No,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,505.2873,522.1282,513.3068,528.5437,522.9301,511.0407,532.4879,524.0955,551.1376,514.7706
485489,Vietnam,Viet Nam,Female,She did not complete <ISCED level 1>,No,No,NaN,No,"Other (e.g. home duties, retired)",<ISCED level 3A>,...,532.3506,483.1034,479.9261,459.2741,488.6635,530.6229,473.7411,477.4711,477.4711,505.4457

In [6]:
pisa_score = pisa_score.drop(['Unnamed: 0'], axis =1)

In [8]:
ISCED_level_6 = pisa_score[pisa_score['ST14Q01'] == 'Yes']
ISCED_level_5A = pisa_score[(pisa_score['ST14Q01'] == 'No') & (pisa_score['ST14Q02'] == 'Yes')]
ISCED_level_5B = pisa_score[(pisa_score['ST14Q01'] == 'No') & (pisa_score['ST14Q02'] == 'No')&(pisa_score['ST14Q03'] == 'Yes')]
ISCED_level_4 = pisa_score[(pisa_score['ST14Q01'] == 'No') & (pisa_score['ST14Q02'] == 'No')&(pisa_score['ST14Q03'] == 'No')&(pisa_score['ST14Q04'] == 'Yes')]

In [12]:
indexes_level6 = ISCED_level_6.index.tolist()
for i in indexes_level6:
    pisa_score['ST13Q01'][i] = '<ISCED level 6>'

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [13]:
indexes_level5A = ISCED_level_5A.index.tolist()
for i in indexes_level5A:
    pisa_score['ST13Q01'][i] = '<ISCED level 5A>'

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [14]:
indexes_level5B = ISCED_level_5B.index.tolist()
for i in indexes_level5B:
    pisa_score['ST13Q01'][i] = '<ISCED level 5B>'

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [15]:
indexes_level4 = ISCED_level_4.index.tolist()
for i in indexes_level4:
    pisa_score['ST13Q01'][i] = '<ISCED level 4>'

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [16]:
ISCED_level_6 = pisa_score[pisa_score['ST18Q01'] == 'Yes']
ISCED_level_5A = pisa_score[(pisa_score['ST18Q01'] == 'No') & (pisa_score['ST18Q02'] == 'Yes')]
ISCED_level_5B = pisa_score[(pisa_score['ST18Q01'] == 'No') & (pisa_score['ST18Q02'] == 'No')&(pisa_score['ST18Q03'] == 'Yes')]
ISCED_level_4 = pisa_score[(pisa_score['ST18Q01'] == 'No') & (pisa_score['ST18Q02'] == 'No')&(pisa_score['ST18Q03'] == 'No')&(pisa_score['ST18Q04'] == 'Yes')]

In [17]:
indexes_level6 = ISCED_level_6.index.tolist()
for i in indexes_level6:
    pisa_score['ST17Q01'][i] = '<ISCED level 6>'

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [18]:
indexes_level5A = ISCED_level_5A.index.tolist()
for i in indexes_level5A:
    pisa_score['ST17Q01'][i] = '<ISCED level 5A>'

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [19]:
indexes_level5B = ISCED_level_5B.index.tolist()
for i in indexes_level5B:
    pisa_score['ST17Q01'][i] = '<ISCED level 5B>'

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [20]:
indexes_level4 = ISCED_level_4.index.tolist()
for i in indexes_level4:
    pisa_score['ST17Q01'][i] = '<ISCED level 4>'

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [21]:
pisa_score = pisa_score.drop(['ST14Q01', 'ST14Q02', 'ST14Q03', 'ST14Q04', 'ST18Q01', 'ST18Q02', 'ST18Q03', 'ST18Q04'], axis =1)

In [23]:
pisa_score.to_csv('pisa12.csv')